### ISSUE TITLE
Design Decisions

### ISSUE THREAD

**Issue by ToJen** [herkyl/patchwerk#1]
Hey, thanks for creating this library. Just curious to know what updates/bug fixes were made from https://github.com/mattbaird/jsonpatch. Also are there any vulnerabilities in patchwerk?

**Comment by herkyl** [comment]
Hello @ToJen ! Sorry for the late reply, I somehow missed your question.

There is a great variety of bug fixes that I implemented from https://github.com/mattbaird/jsonpatch. After building some tests there was a lot that didn't work as intended. I ended up using jsonpatch as more of an entry point and redesigned the library in many places. Unfortunately, I don't have a full list of what changed.

There are no vulnerabilities that I know of (which doesn't mean that there aren't any) but patchwerk is intended to be used on user generated content.
